name: Module Requirements
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Requirements
        id: install_reqs

        uses: ryan-rozario/pipreqs-action-cpy@master

        with:
          REQUIREMENT_PATH: ./requirements.txt
